Document: slang
Title: Debian slang Manual
Author: <insert document author here>
Abstract: This manual describes what slang is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/slang/slang.sgml.gz

Format: postscript
Files: /usr/share/doc/slang/slang.ps.gz

Format: text
Files: /usr/share/doc/slang/slang.text.gz

Format: HTML
Index: /usr/share/doc/slang/html/index.html
Files: /usr/share/doc/slang/html/*.html
